FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY setup.py .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install .

EXPOSE 8501

CMD [
    "streamlit",
    "run",
    "streamlit_app.py",
    "--server.address=0.0.0.0",
    "--server.port=8501"
]